name: e2e-trigger

on:
  issue_comment:
    types: [created]
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
  push:
    branches:
      - master

env:
  RUN_COMMAND: /run-e2e
  SKIP_COMMAND: /skip-e2e
  SKIP_LABEL: e2e/skip
  CHECK_NAME: e2e

permissions:
  statuses: write
  pull-requests: write
  actions: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    name: Pull request evaluate
    steps:
      - name: Set check status to pending
        if: contains(github.event.pull_request.labels.*.name, env.SKIP_LABEL) === false
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          context: ${{ env.CHECK_NAME }}
          status: pending
          description: E2E tests are still to be run

      - name: Skipped / Set check status to success
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        if: contains(github.event.pull_request.labels.*.name, env.SKIP_LABEL)
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          context: ${{ env.CHECK_NAME }}
          status: success
          description: E2E tests are skipped

  comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment'
    name: Comment evaluate
    steps:
      - name: Determine if e2e should run
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        id: decision
        with:
          script: |
            core.setOutput('should_run', context.payload.comment?.body?.includes(process.env.RUN_COMMAND) === true)
            core.setOutput('should_skip', context.payload.comment?.body?.includes(process.env.SKIP_COMMAND) === true)

      - name: Add label to skip e2e test
        if: steps.decision.outputs.should_skip == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["e2e/skip"]
            })

      - name: Retrieve pull request data
        if: steps.decision.outputs.should_run == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        id: pr_data
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
            })
            core.setOutput('ref', pr.head.ref)
            core.setOutput('commit_sha', pr.head.sha)

      - name: Trigger e2e workflow
        if: steps.decision.outputs.should_run == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'e2e.yml',
              ref: "${{ steps.pr_data.outputs.ref }}",
              inputs: {
                debug: context.payload.comment?.body?.includes(`${process.env.RUN_COMMAND} debug`) === true,
                'debug-pr-number': `${context.payload.issue.number}`,
                'status-comment-id': `${context.payload.comment.id}`,
                'status-commit-sha': "${{ steps.pr_data.outputs.commit_sha }}",
                'status-check-name': process.env.CHECK_NAME,
              },
            })

  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Push evaluate
    steps:
      - name: Set check status to pending
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
          context: ${{ env.CHECK_NAME }}
          status: pending
          description: E2E tests are still to be run

      - name: Trigger e2e workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'e2e.yml',
              ref: context.ref,
              inputs: {
                'status-commit-sha': context.sha,
                'status-check-name': process.env.CHECK_NAME,
              },
            })
