name: Run Tests on PR Label

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - labeled
      - synchronize

jobs:

  test:
    runs-on: ubuntu-latest
    name: Test
    permissions:
      contents: read
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Use the comment-reaction-approval action
        uses: ./.github/actions/comment-reaction-approval
        id: cra
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: "foo"
          wait-timeout-seconds: 60
          check-interval-seconds: 5

      - name: Print
        run: |
          cat <<EOF
          ${{ toJson(steps.cra.outputs) }}
          EOF
